name: Sheenam Build Pipline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v2
    - name: Seting Up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.402
        include-prerelease: false
    - name: Restarting Nutget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
